const stringToFindArr = [
  "monster trucks",
  "bicycles",
  "scary clowns",
  "fish",
  "penguins",
  "red apples",
  "cry",
  "laughing",
  "hairy persons",
  "street signs",
  "dogs with fleas",
  "pigs",
  "a stinkbug",
  "a pink rat",
  "food",
  "colour",
  "starfish",
  "construction workers",
  "nincompoops",
  "bucket",
  "a fishing license",
  "motor vehicles",
  "a crosswalk",
  "traffic lights",
  "mountains",
  "monuments",
  "religious figures",
  "houses",
  "false idols",
  "bridges",
  "water",
  "sky",
  "a fire hydrant",
  "public transportation",
  "buses",
  "trumpets",
  "${401 unauthorized request - user r...",
  "a mother",
  "a pope",
  "",
  "noise",
  "a Norwegian",
  "pyramids",
  "a fruit",
  "the Golden Gate Bridge",
  "mythological creatures",
  "classical paintings",
  "Renaissance statues",
  "famous American actors",
  "soup (not stew)",
  "headphones",
  "billionaires",
  "Barenaked Ladies",
  "Melanoides tuberculata",
  "world leaders",
  "country flags",
  "guitars",
  "street fighters",
  "gazebos",
  "a garden flower",
  "Greek philosophers",
  "Zdzisław Beksiński",
  "Canadian rye",
  "androids",
  "firefighters",
  "Spotify",
  "u",
  "evil doers",
  "waste management",
];

export default stringToFindArr;
